nohup: ignoring input
19000551
(212219, 8)
Daily download completed successfully. Running DNS lookup...
Starting...
domain_update_daily2023-12-06.parquet
  + Exception Group Traceback (most recent call last):
  |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 365, in <module>
  |     df = asyncio.run(execute_fetcher_tasks(urls_to_fetch, file, len))
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
  |     return runner.run(main)
  |            ^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
  |     return future.result()
  |            ^^^^^^^^^^^^^^^
  |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 89, in execute_fetcher_tasks
  |     async with asyncio.TaskGroup() as g:
  |   File "/usr/lib/python3.11/asyncio/taskgroups.py", line 147, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (30 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 161, in fetch_url
    |     create_date = await get_create_date(filename)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 341, in get_create_date
    |     date = str(datetime.datetime.strptime(b, date_format))
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    |     raise ValueError("time data %r does not match format %r" %
    | ValueError: time data '023-12-06' does not match format '%Y-%m-%d'
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 161, in fetch_url
    |     create_date = await get_create_date(filename)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 341, in get_create_date
    |     date = str(datetime.datetime.strptime(b, date_format))
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    |     raise ValueError("time data %r does not match format %r" %
    | ValueError: time data '023-12-06' does not match format '%Y-%m-%d'
    +---------------- 3 ----------------
    | Traceback (most recent call last):
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 161, in fetch_url
    |     create_date = await get_create_date(filename)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 341, in get_create_date
    |     date = str(datetime.datetime.strptime(b, date_format))
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    |     raise ValueError("time data %r does not match format %r" %
    | ValueError: time data '023-12-06' does not match format '%Y-%m-%d'
    +---------------- 4 ----------------
    | Traceback (most recent call last):
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 161, in fetch_url
    |     create_date = await get_create_date(filename)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 341, in get_create_date
    |     date = str(datetime.datetime.strptime(b, date_format))
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    |     raise ValueError("time data %r does not match format %r" %
    | ValueError: time data '023-12-06' does not match format '%Y-%m-%d'
    +---------------- 5 ----------------
    | Traceback (most recent call last):
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 161, in fetch_url
    |     create_date = await get_create_date(filename)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 341, in get_create_date
    |     date = str(datetime.datetime.strptime(b, date_format))
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    |     raise ValueError("time data %r does not match format %r" %
    | ValueError: time data '023-12-06' does not match format '%Y-%m-%d'
    +---------------- 6 ----------------
    | Traceback (most recent call last):
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 161, in fetch_url
    |     create_date = await get_create_date(filename)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 341, in get_create_date
    |     date = str(datetime.datetime.strptime(b, date_format))
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    |     raise ValueError("time data %r does not match format %r" %
    | ValueError: time data '023-12-06' does not match format '%Y-%m-%d'
    +---------------- 7 ----------------
    | Traceback (most recent call last):
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 161, in fetch_url
    |     create_date = await get_create_date(filename)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 341, in get_create_date
    |     date = str(datetime.datetime.strptime(b, date_format))
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    |     raise ValueError("time data %r does not match format %r" %
    | ValueError: time data '023-12-06' does not match format '%Y-%m-%d'
    +---------------- 8 ----------------
    | Traceback (most recent call last):
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 161, in fetch_url
    |     create_date = await get_create_date(filename)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 341, in get_create_date
    |     date = str(datetime.datetime.strptime(b, date_format))
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    |     raise ValueError("time data %r does not match format %r" %
    | ValueError: time data '023-12-06' does not match format '%Y-%m-%d'
    +---------------- 9 ----------------
    | Traceback (most recent call last):
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 161, in fetch_url
    |     create_date = await get_create_date(filename)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 341, in get_create_date
    |     date = str(datetime.datetime.strptime(b, date_format))
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    |     raise ValueError("time data %r does not match format %r" %
    | ValueError: time data '023-12-06' does not match format '%Y-%m-%d'
    +---------------- 10 ----------------
    | Traceback (most recent call last):
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 161, in fetch_url
    |     create_date = await get_create_date(filename)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 341, in get_create_date
    |     date = str(datetime.datetime.strptime(b, date_format))
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    |     raise ValueError("time data %r does not match format %r" %
    | ValueError: time data '023-12-06' does not match format '%Y-%m-%d'
    +---------------- 11 ----------------
    | Traceback (most recent call last):
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 161, in fetch_url
    |     create_date = await get_create_date(filename)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 341, in get_create_date
    |     date = str(datetime.datetime.strptime(b, date_format))
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    |     raise ValueError("time data %r does not match format %r" %
    | ValueError: time data '023-12-06' does not match format '%Y-%m-%d'
    +---------------- 12 ----------------
    | Traceback (most recent call last):
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 161, in fetch_url
    |     create_date = await get_create_date(filename)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 341, in get_create_date
    |     date = str(datetime.datetime.strptime(b, date_format))
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    |     raise ValueError("time data %r does not match format %r" %
    | ValueError: time data '023-12-06' does not match format '%Y-%m-%d'
    +---------------- 13 ----------------
    | Traceback (most recent call last):
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 161, in fetch_url
    |     create_date = await get_create_date(filename)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 341, in get_create_date
    |     date = str(datetime.datetime.strptime(b, date_format))
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    |     raise ValueError("time data %r does not match format %r" %
    | ValueError: time data '023-12-06' does not match format '%Y-%m-%d'
    +---------------- 14 ----------------
    | Traceback (most recent call last):
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 161, in fetch_url
    |     create_date = await get_create_date(filename)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 341, in get_create_date
    |     date = str(datetime.datetime.strptime(b, date_format))
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    |     raise ValueError("time data %r does not match format %r" %
    | ValueError: time data '023-12-06' does not match format '%Y-%m-%d'
    +---------------- 15 ----------------
    | Traceback (most recent call last):
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 161, in fetch_url
    |     create_date = await get_create_date(filename)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/dnsproject/asyncio_dns_daily_updates.py", line 341, in get_create_date
    |     date = str(datetime.datetime.strptime(b, date_format))
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    |     raise ValueError("time data %r does not match format %r" %
    | ValueError: time data '023-12-06' does not match format '%Y-%m-%d'
    +---------------- ... ----------------
    | and 15 more exceptions
    +------------------------------------
